Añadido revision de reporte

diff --git a/.github/workflows/ci-cd-banbif.yml b/.github/workflows/ci-cd-banbif.yml
--- a/.github/workflows/ci-cd-banbif.yml
+++ b/.github/workflows/ci-cd-banbif.yml
@@ -61,12 +61,16 @@ jobs:
       with:
         distribution: 'adopt'
         java-version: '21'
-    - name: Install dependencies
-      run: mvn install -DskipTests
-
-    - name: Run tests and generate coverage report
-      run: mvn clean verify -Pcoverage
-
+    - name: Build with Maven
+      run: mvn clean verify
+    - name: Generate JaCoCo Report
+      run: mvn jacoco:report
+    - name: Verify JaCoCo Report
+      run: |
+        if [ ! -f target/jacoco/jacoco.xml ]; then
+          echo "JaCoCo report not found!"
+          exit 1
+        fi
     - name: SonarQube Scan
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
