Añadido revision de reporte

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -62,11 +62,15 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-maven-
       - name: Build with Maven
-        run: |
-          mvn clean verify
+        run: mvn clean verify
       - name: Generate JaCoCo Report
+        run: mvn jacoco:report
+      - name: Verify JaCoCo Report
         run: |
-          mvn jacoco:report
+          if [ ! -f target/site/jacoco/jacoco.xml ]; then
+            echo "JaCoCo report not found!"
+            exit 1
+          fi
       - name: SonarQube Scan
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
